using System;
using System.IO;
using System.Security.Cryptography;
using System.Linq;
using System.Net;

namespace LibProtection
{
	public static class Core
	{
		public static void Init (string gmode)
		{
			byte[] hash; 
			byte[] hashnew;
			hash = File.ReadAllBytes ("protection.bin");
			hashnew = MD5.Create ().ComputeHash (File.ReadAllBytes (AppDomain.CurrentDomain.FriendlyName));

			if (!hash.SequenceEqual (hashnew)) {
				if (gmode == "-iG") {
					System.Windows.Forms.MessageBox.Show ("The software is compromised\n" +
					"IP address is : " + Dns.GetHostEntry (Dns.GetHostName ()).AddressList [0] + "\n" +
					"please contact software vendor to provide new copy\n\n" +
					"Warning generated by DotProtector.LibProtection Module\n" +
					"Copyleft 2015 Abhimanbhau Kolte");
				} else {
					System.Windows.Forms.MessageBox.Show ("You smartass, nice try on modding the app\n" +
					"By the time you read this message, I am uploading your system info to developer" +
					"IP address is : " + Dns.GetHostEntry (Dns.GetHostName ()).AddressList [0] + "\n" +
					"please contact software vendor to provide new copy\n\n" +
					"Warning generated by DotProtector.LibProtection Module\n" +
					"Copyleft 2015 Abhimanbhau Kolte");
				}
				throw new Exception ("DotPatcher.LibProtection -> APP_COMPROMISED_EXCEPTION");
			}
		}
	}
	
}
